apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.TTY/wg: "true"
    io.podman.annotations.autoremove/wg: "FALSE"
    io.podman.annotations.init/wg: "FALSE"
    io.podman.annotations.privileged/wg: "FALSE"
    io.podman.annotations.publish-all/wg: "FALSE"
  labels:
    app: wg-pod
  name: wg-pod
spec:
  automountServiceAccountToken: false
  containers:
  - env:
    #- name: webhook
    #  value: <WEBHOOK_URL>
    ## Either "bpf" or "nflog"
    #- name: monitor
    #  value: <MONITOR_TYPE>
    ## Needed in bpf mode
    ## Usually public facing interface
    #- name: interface
    #  value: <INTERFACE>
    ## Needed in bpf mode
    ## BPF filter for PCAP
    #- name: filter
    #  value: <FILTER>
    ## Needed in nflog mode
    ## Netfilter group to listen to
    #- name: group
    #  value: <GROUP>
    image: localhost/wg:latest
    name: wg
    ports:
    - containerPort: 3000
      hostPort: 3000
      protocol: UDP
    securityContext:
      capabilities:
        add:
        - CAP_NET_ADMIN
        - CAP_NET_RAW
        drop:
        - CAP_MKNOD
        - CAP_AUDIT_WRITE
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /etc/wireguard
      name: etc-wireguard-host-0
  enableServiceLinks: false
  restartPolicy: always
  volumes:
  - hostPath:
      path: /etc/wireguard
      type: Directory
    name: etc-wireguard-host-0
